# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: macos-clean-tree
description: LuxCore Python Wheels - Clean/update source tree for Macos build
runs:
  using: 'composite'
  steps:

    - name: Find sed
      shell: 'bash'
      run: |
        if [[ $RUNNER_OS == "macOS" ]]; then
          echo "SED=gsed" >> $GITHUB_ENV
        else
          echo "SED=sed" >> $GITHUB_ENV
        fi

    - name: Remove OpenColorIO
      shell: 'bash'
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        $SED -i "/add_library(opencolorio/d" src/slg/CMakeLists.txt

