# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-build-system
description: LuxCore Python Wheels - Build boost-python & boost-numpy for Windows build
runs:
  using: 'composite'
  steps:
    # Debug
    - name: Set up yasm (bash)
      working-directory: ${{ github.workspace }}/scripts
      run: |
        . /c/Miniconda/etc/profile.d/conda.sh
        #conda install yasm  TODO Debug
        cp yasm /usr/bin
      shell: bash

    - name: Set up yasm (pwsh)
      working-directory: ${{ github.workspace }}/scripts
      run: |
        Set-Alias -Name yasm -Value "echo 'YASM!'"
      shell: pwsh

    #- name: Test yasm
      #run: |
        #echo "Test yasm"
        #yasm --version
      #shell: bash

    #- name: Test yasm
      #run: |
        #yasm
      #shell: pwsh

    #- uses: mxschmitt/action-tmate@v3



    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    # https://github.com/lukka/run-vcpkg
    - uses: lukka/get-cmake@latest

    # TODO should be global?
    - name: Setup sccache
      id: sccache
      uses: mozilla-actions/sccache-action@v0.0.5

    # TODO
    #- uses: ilammy/msvc-dev-cmd@v1

    # Initialize Conan with local packages
    - name: Initialize Conan
      working-directory: ${{ github.workspace }}/LuxCore
      env:
        PKG_CONFIG_PATH: .
        CMAKE_CXX_COMPILER_LAUNCHER: sccache
        CMAKE_C_COMPILER_LAUNCHER: sccache
      run: |
        # Copy profiles
        mkdir -p /c/users/runneradmin/.conan2/profiles
        cp ../conan_profile /c/users/runneradmin/.conan2/profiles/default
        cp ../conan_profile_libvpx /c/users/runneradmin/.conan2/profiles/libvpx

        cp ../conanfile.py .
        unset ORIGINAL_PATH
      shell: bash

    - name: Create libvpx
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        conan create --version=1.13.1 --profile=libvpx ../externals/windows/libvpx
        #conan install --profile=libvpx --build=missing --requires=libvpx/1.13.1 -vvv
      shell: bash

    - name: Create local packages
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        conan create ../externals/windows/oidn
        conan create ../externals/windows/openimageio
      shell: bash
    ##- uses: mxschmitt/action-tmate@v3

    - name: Run conan
      working-directory: ${{ github.workspace }}/LuxCore
      env:
        PKG_CONFIG_PATH: .
        CMAKE_CXX_COMPILER_LAUNCHER: sccache
        CMAKE_C_COMPILER_LAUNCHER: sccache
      run: |
        conan install --build=missing .  -s build_type=Release
      shell: bash

    # Copy config to project
    - name: "Install Config_Windows-Wheel.cmake"
      working-directory: '${{ github.workspace }}'
      run: |
        cp configs/Config_Windows-Wheel.cmake LuxCore/cmake/SpecializedConfig
      shell: bash


    # # Copy CMakePresets to project
    # - name: "Install CMakePresets.json"
    #   working-directory: '${{ github.workspace }}'
    #   run: |
    #     cp CMakePresets.json LuxCore
    #   shell: bash
