# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-build-system
description: LuxCore Python Wheels - Build boost-python & boost-numpy for Windows build
inputs:
  job-id:
    description: 'Job unique identifier (for caching)'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Init environment
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "SCCACHE_C_CUSTOM_CACHE_BUSTER=${{ inputs.job-id }}" >> $GITHUB_ENV
        echo "SCCACHE_CONF=${GITHUB_WORKSPACE}/sccache_config" >> $GITHUB_ENV
        #echo "SCCACHE_DIRECT=False" >> $GITHUB_ENV
        echo "SCCACHE_ERROR_LOG=../../sccache.log" >> $GITHUB_ENV
        # echo "SCCACHE_LOG=debug" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
      shell: bash
    # Debug
    #- uses: mxschmitt/action-tmate@v3

    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    # https://github.com/lukka/run-vcpkg
    - uses: lukka/get-cmake@latest

    - name: Setup sccache
      id: sccache
      uses: mozilla-actions/sccache-action@v0.0.5

    # For main compilation
    - uses: ilammy/msvc-dev-cmd@v1


    # Initialize Conan with local packages
    - name: Initialize Conan
      working-directory: ${{ github.workspace }}/LuxCore
      env:
        PKG_CONFIG_PATH: .
      run: |
        # Copy profiles
        mkdir -p /c/users/runneradmin/.conan2/profiles
        cp ../conan_profile /c/users/runneradmin/.conan2/profiles/default
        cp ../conan_profile_libvpx /c/users/runneradmin/.conan2/profiles/libvpx

        cp ../conanfile.py .
        unset ORIGINAL_PATH
      shell: bash

    #- name: Create libvpx
      #working-directory: ${{ github.workspace }}/LuxCore
      #run: |
        #conan create --version=1.13.1 --profile=libvpx ../externals/windows/libvpx
        ##conan install --profile=libvpx --build=missing --requires=libvpx/1.13.1 -vvv
      #shell: pwsh

    #- name: boost
      #working-directory: ${{ github.workspace }}
      #run: |
        ##echo 'using msvc : 14.3 : "sccache.exe ''${{ env.VCINSTALLDIR }}bin\cl.exe''" : ;' | sed -r 's/\\/\//g'>> /c/users/runneradmin/site-config.jam
        ##cat /c/users/runneradmin/site-config.jam
        #conan install \
          #--requires boost/1.78.0 \
          #--build=boost/1.78.0 \
          #-o boost/*:without_atomic=False \
          #-o boost/*:without_charconv=True \
          #-o boost/*:without_chrono=False \
          #-o boost/*:without_cobalt=True \
          #-o boost/*:without_container=False \
          #-o boost/*:without_context=True \
          #-o boost/*:without_contract=True \
          #-o boost/*:without_coroutine=True \
          #-o boost/*:without_date_time=False \
          #-o boost/*:without_exception=False \
          #-o boost/*:without_fiber=True \
          #-o boost/*:without_filesystem=False \
          #-o boost/*:without_graph=True \
          #-o boost/*:without_graph_parallel=True \
          #-o boost/*:without_iostreams=False \
          #-o boost/*:without_json=True \
          #-o boost/*:without_locale=True \
          #-o boost/*:without_log=True \
          #-o boost/*:without_math=True \
          #-o boost/*:without_mpi=True \
          #-o boost/*:without_nowide=True \
          #-o boost/*:without_program_options=False \
          #-o boost/*:without_python=False \
          #-o boost/*:without_random=False \
          #-o boost/*:without_regex=False \
          #-o boost/*:without_serialization=False \
          #-o boost/*:without_stacktrace=True \
          #-o boost/*:without_system=False \
          #-o boost/*:without_test=True \
          #-o boost/*:without_thread=False \
          #-o boost/*:without_timer=True \
          #-o boost/*:without_type_erasure=True \
          #-o boost/*:without_url=True \
          #-o boost/*:without_wave=True \
          #-o boost/*:magic_autolink=True \
          #-o boost/*:extra_b2_flags=-d0

      #shell: bash

    - name: oidn
      working-directory: ${{ github.workspace }}/externals/windows/oidn
      run: |
        conan source .
        conan install .
        conan build .
        ls
        conan editable add .
        conan editable list
        #conan export-pkg .
      shell: bash

    - name: test
      working-directory: ${{ github.workspace }}/externals/windows/test
      run: |
        conan install --build=missing .  -s build_type=Release
        cmake --preset=conan-release -G ninja .
      shell: bash

    - name: openimageio
      working-directory: ${{ github.workspace }}/externals/windows/openimageio
      run: |
        conan source .
        conan install .
        conan build .
        # conan editable add --name=openimageio --version=2.2.13.1 .
        conan export-pkg .
      shell: bash

    #- uses: mxschmitt/action-tmate@v3

    - name: Run conan
      working-directory: ${{ github.workspace }}/LuxCore
      env:
        PKG_CONFIG_PATH: .
      run: |
        conan install --build=missing .  -s build_type=Release
      shell: bash

    # Copy config to project
    - name: "Install Config_Windows-Wheel.cmake"
      working-directory: '${{ github.workspace }}'
      run: |
        cp configs/Config_Windows-Wheel.cmake LuxCore/cmake/SpecializedConfig
      shell: bash
