# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-build-system
description: LuxCore Python Wheels - Build boost-python & boost-numpy for Windows build
runs:
  using: 'composite'
  steps:
    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    # https://github.com/lukka/run-vcpkg
    - uses: lukka/get-cmake@latest

    # TODO should be global?
    - name: Setup sccache
      id: sccache
      uses: mozilla-actions/sccache-action@v0.0.5

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.${{ matrix.python-minor }}"

    - name: Get yasm
      shell: pwsh
      run: |
        conda install conda-forge::yasm
        yasm --version

    # Initialize Conan
    - name: Initialize Conan
      working-directory: ${{ github.workspace }}/LuxCore
      env:
        PKG_CONFIG_PATH: .
        CMAKE_CXX_COMPILER_LAUNCHER: sccache
        CMAKE_C_COMPILER_LAUNCHER: sccache
      run: |
        yasm --version

        # Copy profile
        mkdir -p /c/users/runneradmin/.conan2/profiles
        cp ../conan_profile /c/users/runneradmin/.conan2/profiles/default
        cp ../conanfile.py .

        # Create local packages (openimageio, oidn)
        conan create ../externals/windows/oidn
        conan create ../externals/windows/openimageio

        # Run conan
        conan install --build=missing .  -s build_type=Release
      shell: bash

    # Copy config to project
    - name: "Install Config_Windows-Wheel.cmake"
      working-directory: '${{ github.workspace }}'
      run: |
        cp configs/Config_Windows-Wheel.cmake LuxCore/cmake/SpecializedConfig
      shell: bash


    # # Copy CMakePresets to project
    # - name: "Install CMakePresets.json"
    #   working-directory: '${{ github.workspace }}'
    #   run: |
    #     cp CMakePresets.json LuxCore
    #   shell: bash
