# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-python-boost
description: LuxCore Python Wheels - Build boost-python & boost-numpy for Windows build
runs:
  using: 'composite'
  steps:
    # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    # https://github.com/lukka/run-vcpkg
    - uses: lukka/get-cmake@latest

    - name: Setup sccache
      if: ${{ runner.os }} == "Windows"
      id: sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      
    # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly.
    # As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
    - uses: ilammy/msvc-dev-cmd@v1

    # Initialize Conan
    - name: Initialize Conan
      working-directory: ${{ github.workspace }}/LuxCore
      run: |
        conan profile detect --force
        conan install . -s build_type=Release

    # TODO
    # # Copy CMakePresets to project
    # - name: "Install CMakePresets.json and vcpkg.json"
    #   working-directory: '${{ github.workspace }}'
    #   run: |
    #     cp vcpkg.json LuxCore
    #     cp CMakePresets.json LuxCore
    #   shell: bash

#    - name: Install Ninja
#      uses: seanmiddleditch/gha-setup-ninja@master
    
    # vcpkg stuff
    - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
      run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
      shell: bash

    # Restore vcpkg from the GitHub Action cache service. Note that packages are restored by vcpkg's binary caching
    # when it is being run afterwards by CMake.
    - name: Restore vcpkg
      uses: actions/cache@v4
      with:
        # The first path is the location of vcpkg: it contains the vcpkg executable and data files, as long as the
        # built package archives (aka binary cache) which are located by VCPKG_DEFAULT_BINARY_CACHE env var.
        # The other paths starting with '!' are exclusions: they contain termporary files generated during the build of the installed packages.
        path: |
          ${{ env._VCPKG_ }}
          !${{ env._VCPKG_ }}/buildtrees
          !${{ env._VCPKG_ }}/packages
          !${{ env._VCPKG_ }}/downloads
          !${{ env._VCPKG_ }}/installed
        # The key is composed in a way that it gets properly invalidated whenever a different version of vcpkg is being used.
        key: |
          ${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}