# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: all-build-system
description: LuxCore Python Wheels - Prepare build
inputs:
  job-id:
    description: 'Job unique identifier (for caching)'
    required: true
    type: string
runs:
  using: 'composite'
  steps:

    # TODO
    #- name: Init environment
      #run: |
        #echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        #echo "SCCACHE_C_CUSTOM_CACHE_BUSTER=${{ inputs.job-id }}" >> $GITHUB_ENV
        #echo "SCCACHE_CONF=${GITHUB_WORKSPACE}/sccache_config" >> $GITHUB_ENV
        #echo "SCCACHE_ERROR_LOG=${{ github.workspace }}/sccache.log" >> $GITHUB_ENV
        ## LogLevel in {error, warn, info, debug, trace}, see parse.rs
        #echo "SCCACHE_LOG=debug" >> $GITHUB_ENV
        #echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
        #echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
        #echo "BOOST_INSTALL_LAYOUT=system" >> $GITHUB_ENV
      #shell: bash

    - uses: lukka/get-cmake@latest
      if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'windows')

    - name: Setup sccache
      if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'windows')
      id: sccache
      uses: mozilla-actions/sccache-action@v0.0.5

    # For windows compilation
    - uses: ilammy/msvc-dev-cmd@v1
      if: startsWith(matrix.os, 'windows')

# TODO
          #CIBW_ENVIRONMENT_LINUX: >-
            #SCCACHE_C_CUSTOM_CACHE_BUSTER='3.${{ matrix.python-minor }}'
            #BOOST_INSTALL_LAYOUT=system
            #PYTHON_TAG='cp3${{ matrix.python-minor }}'
            #Python_ROOT_DIR=/opt/python/cp3${{ matrix.python-minor }}-cp3${{ matrix.python-minor }}
            #Python_DIR=/opt/python/cp3${{ matrix.python-minor }}-cp3${{ matrix.python-minor }}
            #Python_FIND_STRATEGY="LOCATION"
            #CMAKE_C_COMPILER_LAUNCHER="sccache"
            #CMAKE_CXX_COMPILER_LAUNCHER="sccache"
            #
          #CIBW_ENVIRONMENT_WINDOWS: >-
            #SCCACHE_C_CUSTOM_CACHE_BUSTER='3.${{ matrix.python-minor }}'
            #SCCACHE_LOG=debug
            #SKBUILD_CMAKE_ARGS='--preset=conan-release;-G Ninja;--log-level=VERBOSE'
            #SPDLOG_FMT_EXTERNAL=on
            #BOOST_INSTALL_LAYOUT=system
