# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: windows-preparation
description: LuxCore Python Wheels - Prepare environment for Windows build
inputs:
  job-id:
    description: 'Job unique identifier (for caching)'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Export cache information
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Restore pip cache
      uses: actions/cache/restore@v4
      with:
        path: 'c:\users\runneradmin\appdata\local\pip\cache'
        key: ${{ inputs.job-id }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ inputs.job-id }}-pip-

    - name: Update Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      shell: bash
          
    - name: Save pip cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: 'c:\users\runneradmin\appdata\local\pip\cache'
        key: ${{ inputs.job-id }}-pip-${{ hashFiles('**/requirements.txt') }}