# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: LuxCore Python Wheels - Sub-workflow for Windows OS

# Pre-requisites:
# Repo and sub-modules have been checked out
# Python is set up

on:
  workflow_dispatch:
    inputs:
      job-identifier:
        description: 'Job unique identifier (for caching)'
        required: true
        type: string

jobs:
  windows-prepare:
    name: Prepare build environment for Windows
    steps:
      - name: Export cache information
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Restore pip cache
        uses: actions/cache/restore@v4
        with:
          path: 'c:\users\runneradmin\appdata\local\pip\cache'
          key: ${{ runner.os }}-${{ matrix.python-minor }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-minor }}-pip-

      - name: Update Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
            
      - name: Save pip cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: 'c:\users\runneradmin\appdata\local\pip\cache'
          key: ${{ runner.os }}-${{ matrix.python-minor}}-pip-${{ hashFiles('**/requirements.txt') }}